---
# Source: lesta-chart/templates/app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: lesta-app-service
  labels:
    app: lesta-app
spec:
  type: NodePort
  selector:
    app: lesta-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080
---
# Source: lesta-chart/templates/postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
---
# Source: lesta-chart/templates/app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesta-app
  labels:
    app: lesta-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lesta-app
  template:
    metadata:
      labels:
        app: lesta-app
    spec:
      containers:
      - name: app
        image: lesta-start:7.1
        ports:
        - containerPort: 8080
        env:
        - name: API_PORT
          value: "8080"
        - name: DB_URL
          value: "postgres://USER_DB:PWD_DB@postgres:5432/DB"
---
# Source: lesta-chart/templates/app-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lesta-app-ingress
  labels:
    app: lesta-app
spec:
  rules:
  - host: lesta.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lesta-app-service
            port:
              number: 80
