apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.app.type }}
  selector:
    app: {{ .Values.app.name }}
  ports:
  - name: http
    port: {{ .Values.service.app.port }}
    targetPort: {{ .Values.service.app.targetPort }}
    {{- if eq .Values.service.app.type "NodePort" }}
    nodePort: {{ .Values.service.app.nodePort }}
    {{- end }}
